apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: k8s-alertas
  namespace: desafio
spec:
  groups:
  - name: kubernetes-alerts
    rules:
    - alert: HighCPUUsage
      expr: sum(rate(container_cpu_usage_seconds_total{image!=""}[2m])) by (pod) > 0.5
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "Uso alto de CPU detectado em um pod"
        description: "Pod {{ $labels.pod }} est치 usando muita CPU (> 50%)."

    - alert: HighMemoryUsage
      expr: sum(container_memory_usage_bytes{image!=""}) by (pod) > 500000000
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: "Uso alto de mem칩ria detectado em um pod"
        description: "Pod {{ $labels.pod }} est치 usando mais de 500MB de mem칩ria."

    - alert: PodDown
      expr: kube_pod_status_phase{phase="Failed"} > 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Pod caiu"
        description: "O pod {{ $labels.pod }} no namespace {{ $labels.namespace }} falhou."
